### ISSUE TITLE
How can  i highlight a column from a dataframe ? for positive it should be green and for negative it should be red

### ISSUE THREAD

**Issue by shantam199** [amrrs/blogpost_codes#1]
I have used this code -
mdata is data frame
V1 is column name

[mdata.zip](https://github.com/amrrs/blogpost_codes/files/3175888/mdata.zip)

Code - 
mdata$V1 %>% 
  sentiment_by(by = NULL) %>%
  highlight()

**Comment by shantam199** [comment]
mdata.zip has the csv file

**Comment by amrrs** [comment]
Did you get this error?

`Error in nchar(data) : invalid multibyte string, element 26`

**Comment by shantam199** [comment]
Hi Amrrs/Blogpost_codes,

i am getting this error :-

Error in `[.data.table`(y, , list(sentiment =
attributes(x)[["averaging.function"]](sentiment),  :
  attempt to apply non-function

![image](https://user-images.githubusercontent.com/44675984/57681198-dedb0b00-764c-11e9-8bc1-cf94352bcf7a.png)


thanks and regards,
Shantam Malgaonkar

**Comment by amrrs** [comment]
And without highlight do you get the sentiment classified output?

**Comment by amrrs** [comment]
Can you restart your R/Rstudio and run this 

`devtools::install_github("trinker/sentimentr")`

and then try your code?

**Comment by shantam199** [comment]
Hi Amrrs/Blogpost_codes,

I am getting the sentiments

likethese two are working perfectly :-

 mdata$Sentiments = sentiment_by(mdata$V1)

#Extract Sentiment Keywords

mdata$Sentiment_Words = mdata$V1 %>% extract_sentiment_terms()

**Comment by shantam199** [comment]
Hi,

Error in mdata$V1 %>% sentiment_by(by = NULL) %>% highlight() :
  could not find function "%>%"

now i am getting this error.

**Comment by amrrs** [comment]
could you please load `library(tidyverse)` if you have that package and then try this code? Also did you load the pacakge `library(sentimentr)`

**Comment by shantam199** [comment]
Hi Amrrs/Blogpost_codes,

I have  library(tidyverse)

but now again its showing me this error -> Error in `[.data.table`(y, ,
list(sentiment = attributes(x)[["averaging.function"]](sentiment),  :
  attempt to apply non-function

**Comment by amrrs** [comment]
Strange it works for me. Can you share your `sessionInfo()`?

**Comment by amrrs** [comment]
``` r
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS  10.14.4
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.1  magrittr_1.5    tools_3.5.1     htmltools_0.3.6
#>  [5] yaml_2.2.0      Rcpp_1.0.1      stringi_1.4.3   rmarkdown_1.11 
#>  [9] highr_0.8       knitr_1.22      stringr_1.4.0   xfun_0.6       
#> [13] digest_0.6.18   evaluate_0.13
```

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by shantam199** [comment]
Hi,


What is this?is that running on your system?

**Comment by amrrs** [comment]
Just you can run `sessionInfo()` and paste your results here

**Comment by shantam199** [comment]
Hi Amrrs/Blogpost_codes,

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252
[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C
[5] LC_TIME=English_India.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] tidyselect_0.2.5        tidyr_0.8.3             magrittr_1.5
 [4] wordcloud2_0.2.1        sentimentr_2.7.1        SentimentAnalysis_1.3-3
 [7] stringr_1.4.0           reshape2_1.4.3          dplyr_0.8.0.1
[10] SnowballC_0.6.0         data.table_1.11.8       syuzhet_1.0.4
[13] wordcloud_2.6           RColorBrewer_1.1-2      tm_0.7-6
[16] NLP_0.2-0               httr_1.4.0              ROAuth_0.9.6
[19] reshape_0.8.8

loaded via a namespace (and not attached):
 [1] textshape_1.6.0  slam_0.1-45      purrr_0.2.5      lattice_0.20-35
generics_0.0.2
 [6] htmltools_0.3.6  yaml_2.2.0       rlang_0.3.1      pillar_1.3.1
 textclean_0.9.3
[11] glue_1.3.0       lexicon_1.2.1    plyr_1.8.4       gtable_0.3.0
 htmlwidgets_1.3
[16] qdapRegex_0.7.2  forcats_0.4.0    parallel_3.5.1   broom_0.5.2
Rcpp_1.0.0
[21] backports_1.1.4  digest_0.6.18    stringi_1.4.3    grid_3.5.1
 tools_3.5.1
[26] bitops_1.0-6     RCurl_1.95-4.12  tibble_2.0.1     crayon_1.3.4
 pkgconfig_2.0.2
[31] xml2_1.2.0       assertthat_0.2.0 rstudioapi_0.10  R6_2.3.0
 nlme_3.1-137
[36] compiler_3.5.1

**Comment by amrrs** [comment]
As you can see above `sentimentr_2.7.1` you are using an older version of the package. you need to update to the latest 
`devtools::install_github("trinker/sentimentr")`

**Comment by shantam199** [comment]
Hi,

after running this command devtools::install_github("trinker/sentimentr")

they are asking me this  -

These packages have more recent versions available.
Which would you like to update?

 1:   All                                    2:   CRAN packages only

 3:   None                                   4:   assertthat (0.2.0  ->
0.2.1 ) [CRAN]
 5:   data.table (1.11.8 -> 1.12.2) [CRAN]   6:   glue       (1.3.0  ->
1.3.1 ) [CRAN]
 7:   pillar     (1.3.1  -> 1.4.0 ) [CRAN]   8:   purrr      (0.2.5  ->
0.3.2 ) [CRAN]
 9:   R6         (2.3.0  -> 2.4.0 ) [CRAN]  10:   Rcpp       (1.0.0  ->
1.0.1 ) [CRAN]
11:   rlang      (0.3.1  -> 0.3.4 ) [CRAN]  12:   tibble     (2.0.1  ->
2.1.1 ) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel

**Comment by amrrs** [comment]
You can enter 2

**Comment by shantam199** [comment]
Hi
I entered  2 and came this -

Error in `[.data.table`(y, , list(sentiment =
attributes(x)[["averaging.function"]](sentiment),  :
  attempt to apply non-function

**Comment by shantam199** [comment]
hI Amrrs/Blogpost_codes,

THANKS, it's WORKING NOW :)


Thanks and Regards,
Shantam Malgaonkar

**Comment by amrrs** [comment]
Great! I'll go ahead and close the issue!

**Comment by amrrs** [comment]
Try with sessionInfo() to see if your package is updated. I don't think so. Did you restart your Rstudio and then install the package?
On May 14, 2019, at 3:11 PM, Shantam Malgaonkar <notifications@github.com<mailto:notifications@github.com>> wrote:
Hi
I entered 2 and came this -

Error in `[.data.table`(y, , list(sentiment =
attributes(x)[["averaging.function"]](sentiment), :
attempt to apply non-function

**Comment by shantam199** [comment]
Yes my package got updated
